sudo: required
dist: trusty
language: python

python:
  - "3.4"
  - "2.7"


install:
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - pip install pytest pytest-cov python-coveralls pytest-xdist coverage #we need this version of coverage for coveralls.io to work
  - pip install pep8 pytest-pep8
  - pip install -r requirements.txt
  - python setup.py install

script:
  PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
  PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;

after_success:
  - coveralls
